name: Publish

on:
  release:
    types: [published]
  pull_request:
    types: closed
    branches:
      - master

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: 'true'
      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: myuser@users.noreply.github.com
          ACTION_NAME: myPushingUser
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: temp_release_notes
          OWNER: yourGitHubOrganisation
          REPO_NAME: patent-view-api
          SKIP_MD: README.md
